CREATE TABLE CTDT (
    MaCTDT INT IDENTITY (1, 1) PRIMARY KEY,
    MaNganh NVARCHAR(10) NOT NULL,
    MaKhoaTS NVARCHAR(10) NOT NULL,
    TenCTDT NVARCHAR (200) NOT NULL,
    NamBanHanh INT NOT NULL,
    CONSTRAINT FK_CTDT_Nganh FOREIGN KEY (MaNganh) REFERENCES Nganh (MaNganh),
    CONSTRAINT FK_CTDT_KTS FOREIGN KEY (MaKhoaTS) REFERENCES KhoaTuyenSinh (MaKhoaTS)
);

CREATE TABLE CTDT_ChiTiet (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaCTDT INT NOT NULL,
    MaHP NVARCHAR(10) NOT NULL,
    HocKyDuKien INT NOT NULL,
    BatBuoc BIT NOT NULL DEFAULT 1,
    NhomTuChon NVARCHAR (50) NULL,
    CONSTRAINT FK_CTDTC_CTDT FOREIGN KEY (MaCTDT) REFERENCES CTDT (MaCTDT),
    CONSTRAINT FK_CTDTC_HP FOREIGN KEY (MaHP) REFERENCES HocPhan (MaHP)
);

CREATE TABLE TienQuyet (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaHP NVARCHAR(10) NOT NULL,
    MaHP_TienQuyet NVARCHAR(10) NOT NULL,
    CONSTRAINT FK_TQ_HP FOREIGN KEY (MaHP) REFERENCES HocPhan (MaHP),
    CONSTRAINT FK_TQ_HP_TQ FOREIGN KEY (MaHP_TienQuyet) REFERENCES HocPhan (MaHP)
);