CREATE TABLE LopHocPhan (
    MaLHP NVARCHAR(20) NOT NULL PRIMARY KEY,
    MaHP NVARCHAR(10) NOT NULL,
    MaHK NVARCHAR(10) NOT NULL,
    MaNam NVARCHAR(10) NOT NULL,
    MaGV NVARCHAR(10) NOT NULL,
    MaPhong NVARCHAR(10) NOT NULL,
    MaCa NVARCHAR(10) NOT NULL,
    ThuTrongTuan TINYINT NOT NULL, -- 2..7
    SiSoToiDa INT NOT NULL,
    GhiChu NVARCHAR (200) NULL,
    CONSTRAINT FK_LHP_HP FOREIGN KEY (MaHP) REFERENCES HocPhan (MaHP),
    CONSTRAINT FK_LHP_HK FOREIGN KEY (MaHK) REFERENCES HocKy (MaHK),
    CONSTRAINT FK_LHP_NH FOREIGN KEY (MaNam) REFERENCES NamHoc (MaNam),
    CONSTRAINT FK_LHP_GV FOREIGN KEY (MaGV) REFERENCES GiangVien (MaGV),
    CONSTRAINT FK_LHP_PH FOREIGN KEY (MaPhong) REFERENCES PhongHoc (MaPhong),
    CONSTRAINT FK_LHP_CA FOREIGN KEY (MaCa) REFERENCES CaHoc (MaCa)
);

CREATE TABLE DangKyHocPhan (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaSV NVARCHAR(10) NOT NULL,
    MaLHP NVARCHAR(20) NOT NULL,
    NgayDangKy DATETIME NOT NULL DEFAULT GETDATE (),
    TrangThai NVARCHAR (50) NOT NULL DEFAULT N'Đăng ký',
    CONSTRAINT FK_DKHP_SV FOREIGN KEY (MaSV) REFERENCES SinhVien (MaSV),
    CONSTRAINT FK_DKHP_LHP FOREIGN KEY (MaLHP) REFERENCES LopHocPhan (MaLHP)
);