CREATE TABLE Diem (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaSV NVARCHAR(10) NOT NULL,
    MaLHP NVARCHAR(20) NOT NULL,
    DiemQT DECIMAL(4, 2) NULL,
    DiemGK DECIMAL(4, 2) NULL,
    DiemCK DECIMAL(4, 2) NULL,
    DiemTK DECIMAL(4, 2) NULL,
    DiemChu NVARCHAR (2) NULL,
    DiemHe4 DECIMAL(3, 2) NULL,
    KetQua NVARCHAR (20) NULL, -- "Đạt" / "Không đạt"
    NgayCapNhat DATETIME NOT NULL DEFAULT GETDATE (),
    NguoiNhap NVARCHAR(50) NULL,
    CONSTRAINT FK_Diem_SV FOREIGN KEY (MaSV) REFERENCES SinhVien (MaSV),
    CONSTRAINT FK_Diem_LHP FOREIGN KEY (MaLHP) REFERENCES LopHocPhan (MaLHP),
    CONSTRAINT CK_Diem_DiemQT CHECK (DiemQT IS NULL OR (DiemQT >= 0 AND DiemQT <= 10)),
    CONSTRAINT CK_Diem_DiemGK CHECK (DiemGK IS NULL OR (DiemGK >= 0 AND DiemGK <= 10)),
    CONSTRAINT CK_Diem_DiemCK CHECK (DiemCK IS NULL OR (DiemCK >= 0 AND DiemCK <= 10))
);

CREATE TABLE PhucKhao (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaSV NVARCHAR(10) NOT NULL,
    MaLHP NVARCHAR(20) NOT NULL,
    LyDo NVARCHAR (500) NOT NULL,
    TrangThai NVARCHAR (50) NOT NULL DEFAULT N'Chờ xử lý',
    NgayGui DATETIME NOT NULL DEFAULT GETDATE (),
    NgayXuLy DATETIME NULL,
    GhiChuXuLy NVARCHAR (500) NULL,
    CONSTRAINT FK_PK_SV FOREIGN KEY (MaSV) REFERENCES SinhVien (MaSV),
    CONSTRAINT FK_PK_LHP FOREIGN KEY (MaLHP) REFERENCES LopHocPhan (MaLHP)
);

CREATE TABLE DieuKienTotNghiep (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaNganh NVARCHAR(10) NOT NULL,
    MaKhoaTS NVARCHAR(10) NOT NULL,
    SoTinChiToiThieu INT NOT NULL,
    DiemTBTichLuyToiThieu DECIMAL(3, 2) NOT NULL,
    CONSTRAINT FK_DKTN_Nganh FOREIGN KEY (MaNganh) REFERENCES Nganh (MaNganh),
    CONSTRAINT FK_DKTN_KTS FOREIGN KEY (MaKhoaTS) REFERENCES KhoaTuyenSinh (MaKhoaTS)
);

CREATE TABLE XetTotNghiep (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    MaSV NVARCHAR(10) NOT NULL,
    LanXet INT NOT NULL,
    KetQua NVARCHAR (50) NOT NULL, -- "Đủ điều kiện", "Chưa đủ điều kiện"
    LyDo NVARCHAR (500) NULL,
    NgayXet DATETIME NOT NULL DEFAULT GETDATE (),
    CONSTRAINT FK_XTN_SV FOREIGN KEY (MaSV) REFERENCES SinhVien (MaSV)
);