CREATE TABLE ThongBao (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    TieuDe NVARCHAR (200) NOT NULL,
    NoiDung NVARCHAR (MAX) NOT NULL,
    NguoiGui NVARCHAR(50) NOT NULL,
    NgayGui DATETIME NOT NULL DEFAULT GETDATE ()
);

CREATE TABLE ThongBao_NguoiNhan (
    IdThongBao INT NOT NULL,
    TenDangNhap NVARCHAR(50) NOT NULL,
    DaDoc BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (IdThongBao, TenDangNhap),
    CONSTRAINT FK_TBNN_TB FOREIGN KEY (IdThongBao) REFERENCES ThongBao (Id),
    CONSTRAINT FK_TBNN_TK FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan (TenDangNhap)
);

CREATE TABLE LogHeThong (
    Id INT IDENTITY (1, 1) PRIMARY KEY,
    TenDangNhap NVARCHAR(50) NOT NULL,
    HanhDong NVARCHAR (200) NOT NULL,
    ThoiGian DATETIME NOT NULL DEFAULT GETDATE (),
    ChiTiet NVARCHAR (MAX) NULL
);